name       : zam-plugins
version    : 4.1
release    : 1
source     :
    - git|https://github.com/zamaudio/zam-plugins.git : 4.1
homepage   : https://www.zamaudio.com/?p=976
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Collection of LADSPA/LV2/VST/JACK audio plugins for high-quality processing
description: |
    Collection of LADSPA/LV2/VST/JACK audio plugins for high-quality processing.
builddeps  :
    - pkgconfig(fftw3f)
    - pkgconfig(gl)
    - pkgconfig(jack)
    - pkgconfig(lv2)
    - pkgconfig(samplerate)
    - pkgconfig(x11)
    - ladspa-devel
    - zita-convolver-devel
build      : |
    export HAVE_ZITA_CONVOLVER=true
    %make
install    : |
    %make_install PREFIX=%PREFIX%
